name = "idkaboutbytes/basicpane"
version = "1.0.4"
description = "BasicPane package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/basicpane"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Observable = { repo = "idkaboutbytes/observable", rev = "v1.0.3" }
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.5" }
Brio = { repo = "idkaboutbytes/brio", rev = "v1.2.3" }
DuckTypeUtils = { repo = "idkaboutbytes/ducktypeutils", rev = "v1.0.5" }
Maid = { repo = "idkaboutbytes/maid", rev = "v1.1.6" }
Rx = { repo = "idkaboutbytes/rx", rev = "v1.0.7" }
ValueObject = { repo = "idkaboutbytes/valueobject", rev = "v1.0.8" }
